"""test

Revision ID: 3335c4f69569
Revises: 5ed023b53592
Create Date: 2026-01-25 17:08:17.829705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3335c4f69569'
down_revision: Union[str, Sequence[str], None] = '5ed023b53592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'difficulty')
    op.drop_column('problems', 'subject')
    op.drop_column('problems', 'correct_answer')
    op.drop_column('problems', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('correct_answer', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
