"""Add new field

Revision ID: 5ed023b53592
Revises: 2423e1d60a98
Create Date: 2026-01-25 16:32:21.781959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed023b53592'
down_revision: Union[str, Sequence[str], None] = '2423e1d60a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'subject')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
