"""Initial migration

Revision ID: d185016e9dbb
Revises: 
Create Date: 2026-01-25 16:16:50.082030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd185016e9dbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('registration_codes')
    op.drop_table('math_problems')
    op.drop_table('variant_answers')
    op.drop_table('informatics_problems')
    op.drop_table('variants')
    op.add_column('categories', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'timed_attempts', 'problems', ['problem_id'], ['id'])
    op.create_foreign_key(None, 'user_solutions', 'problems', ['problem_id'], ['id'])
    op.drop_column('user_solutions', 'subject')
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL")
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_yandex_id_key'), 'users', type_='unique')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'auth_type')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auth_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_yandex_id_key'), 'users', ['yandex_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.add_column('user_solutions', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_solutions', type_='foreignkey')
    op.drop_constraint(None, 'timed_attempts', type_='foreignkey')
    op.drop_column('categories', 'description')
    op.create_table('variants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('variant_token', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('problems_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('variants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('variants_pkey')),
    sa.UniqueConstraint('variant_token', name=op.f('variants_variant_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('informatics_problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problem_image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('solution_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solution_image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('informatics_problems_pkey'))
    )
    op.create_table('variant_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_answer', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('variant_answers_variant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('variant_answers_pkey'))
    )
    op.create_table('math_problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problem_image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('solution_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solution_image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('math_problems_pkey'))
    )
    op.create_table('registration_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('telegram_username', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('registration_codes_pkey')),
    sa.UniqueConstraint('code', name=op.f('registration_codes_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('problems')
    # ### end Alembic commands ###
